---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [1]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [2]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [3]:
def answer_one():
    return df['Gold'].idxmax()
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [9]:
def answer_two():
    df['q2'] = df['Gold'] - df['Gold.1']
    return df['q2'].idxmax()
answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [11]:
df[df['Gold']>0][df['Gold.1']>0]

C:\Users\wanli\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


# Summer  Gold  Silver  Bronze  Total  # Winter  \
Australia                     25   139     152     177    468        18   
Austria                       26    18      33      35     86        22   
Belarus                        5    12      24      39     75         6   
Belgium                       25    37      52      53    142        20   
Bulgaria                      19    51      85      78    214        19   
Canada                        25    59      99     121    279        22   
China                          9   201     146     126    473        10   
Croatia                        6     6       7      10     23         7   
Czech Republic                 5    14      15      15     44         6   
Czechoslovakia                16    49      49      45    143        16   
Estonia                       11     9       9      15     33         9   
Finland                       24   101      84     117    302        22   
France                        27   202     223     246    671        22   
Germany                       15   174     182     217    573        11   
United Team of Germany         3    28      54      36    118         3   
East Germany                   5   153     129     127    409         6   
West Germany                   5    56      67      81    204         6   
Great Britain                 27   236     272     272    780        22   
Italy                         26   198     166     185    549        22   
Japan                         21   130     126     142    398        20   
Kazakhstan                     5    16      17      19     52         6   
South Korea                   16    81      82      80    243        17   
Netherlands                   25    77      85     104    266        20   
Norway                        24    56      49      43    148        22   
Poland                        20    64      82     125    271        22   
Russia                         5   132     121     142    395         6   
Soviet Union                   9   395     319     296   1010         9   
Unified Team                   1    45      38      29    112         1   
Slovakia                       5     7       9       8     24         6   
Slovenia                       6     4       6       9     19         7   
Spain                         22    37      59      35    131        19   
Sweden                        26   143     164     176    483        22   
Switzerland                   27    47      73      65    185        22   
Ukraine                        5    33      27      55    115         6   
United States                 26   976     757     666   2399        22   
Uzbekistan                     5     5       5      10     20         6   

                        Gold.1  Silver.1  Bronze.1  Total.1  # Games  Gold.2  \
Australia                    5         3         4       12       43     144   
Austria                     59        78        81      218       48      77   
Belarus                      6         4         5       15       11      18   
Belgium                      1         1         3        5       45      38   
Bulgaria                     1         2         3        6       38      52   
Canada                      62        56        52      170       47     121   
China                       12        22        19       53       19     213   
Croatia                      4         6         1       11       13      10   
Czech Republic               7         9         8       24       11      21   
Czechoslovakia               2         8        15       25       32      51   
Estonia                      4         2         1        7       20      13   
Finland                     42        62        57      161       46     143   
France                      31        31        47      109       49     233   
Germany                     78        78        53      209       26     252   
United Team of Germany       8         6        

In [12]:
def answer_three():
    df3 = df[df['Gold']>0][df['Gold.1']>0]
    df3['q3'] = (df3['Gold'] - df3['Gold.1'])/df3['Gold.2']
    return df3['q3'].idxmax()
answer_three()

C:\Users\wanli\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [15]:
Points = 3*df['Gold.2'] + 2*df['Silver.2'] + df['Bronze.2']
Points

Afghanistan                           2
Algeria                              27
Argentina                           130
Armenia                              16
Australasia                          22
                                   ... 
Yugoslavia                          171
Independent Olympic Participants      4
Zambia                                3
Zimbabwe                             18
Mixed team                           38
Length: 146, dtype: int64

In [6]:
def answer_four():
    Points = 3*df['Gold.2'] + 2*df['Silver.2'] + df['Bronze.2']
    return Points

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [16]:
census_df = pd.read_csv('census.csv')
census_df

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME            CTYNAME  \
0         40       3         6      1       0  Alabama            Alabama   
1         50       3         6      1       1  Alabama     Autauga County   
2         50       3         6      1       3  Alabama     Baldwin County   
3         50       3         6      1       5  Alabama     Barbour County   
4         50       3         6      1       7  Alabama        Bibb County   
...      ...     ...       ...    ...     ...      ...                ...   
3188      50       4         8     56      37  Wyoming  Sweetwater County   
3189      50       4         8     56      39  Wyoming       Teton County   
3190      50       4         8     56      41  Wyoming       Uinta County   
3191      50       4         8     56      43  Wyoming    Washakie County   
3192      50       4         8     56      45  Wyoming      Weston County   

      CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  \
0           4779736            4780127          4785161  ...   
1             54571              54571            54660  ...   
2            182265             182265           183193  ...   
3             27457              27457            27341  ...   
4             22915              22919            22861  ...   
...             ...                ...              ...  ...   
3188          43806              43806            43593  ...   
3189          21294              21294            21297  ...   
3190          21118              21118            21102  ...   
3191           8533               8533             8545  ...   
3192           7208               7208             7181  ...   

      RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0             0.002295         -0.193196          0.381066          0.582002   
1             7.242091         -2.915927         -3.012349          2.265971   
2            14.832960         17.647293         21.845705         19.243287   
3            -4.728132         -2.500690         -7.056824         -3.904217   
4            -5.527043         -5.068871         -6.201001         -0.177537   
...                ...               ...               ...               ...   
3188          1.072643         16.243199         -5.339774        -14.252889   
3189         -1.589565          0.972695         19.525929         14.143021   
3190        -17.755986         -4.916350         -6.902954        -14.215862   
3191        -11.637475         -0.827815         -2.013502        -17.781491   
3192        -11.752361         -8.040059         12.372583          1.533635   

      RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0            -0.467369     1.030015     0.826644     1.383282     1.724718   
1            -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2            17.197872    15.844176    18.559627    22.727626    20.317142   
3           -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4             0.177258    -5.088389    -4.363636    -5.403729     0.754533   
...                ...          ...          ...          ...          ...   
3188        -14.248864     1.255221    16.243199    -5.295460   -14.075283   
3189         -0.564849     0.654527     2.408578    21.160658    16.308671   
3190        -12.127022   -18.136812    -5.536861    -7.521840   -14.740608   
3191          1.682288   -11.990126    -1.182592    -2.250385   -18.020168   
3192          6.935294   -12.032179    -8.040059    12.372583     1.533635   

      RNETMIG2015  
0        0.712594  
1       -2.187333  
2       18.293499  
3      -10.543299  
4        1.107861  
...           ...  
3188   -14.070195  
3189     1.520747  
3190   -12.606351  
3191     1.441961  
3192     6.935294  

[3193 rows x 100 columns]

In [35]:
census_df.groupby('STNAME').size().idxmax()

'Texas'

In [36]:
def answer_five():
    return census_df.groupby('STNAME').size().idxmax()
answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [49]:
sort=census_df[census_df['STNAME']=='Alabama'].sort_values(by='CENSUS2010POP',ascending=False)
list(sort['CENSUS2010POP'].iloc[1:4])

[658466, 412992, 334811]

In [52]:
def answer_six():
    census_sp = pd.DataFrame(columns=['state','pop'])
    for s in census_df['STNAME'].drop_duplicates():
        sorted_df = census_df[census_df['STNAME']==s].sort_values(by='CENSUS2010POP',ascending=False)
        sp = sorted_df['CENSUS2010POP'].iloc[1:4].sum()
        insertRow = pd.DataFrame([[s,sp]],columns=['state','pop'])
        census_sp = census_sp.append(insertRow,ignore_index=True)
    sorted_sp = census_sp.sort_values(by='pop',ascending=False)
    return list(sorted_sp['state'].iloc[:3])
answer_six()

['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [72]:
cp = census_df[census_df['SUMLEV']==50].loc[:,'CTYNAME':'POPESTIMATE2015']
cp['change'] = abs(cp.loc[:,'POPESTIMATE2010':'POPESTIMATE2015'].max(axis=1)-cp.loc[:,'POPESTIMATE2010':'POPESTIMATE2015'].min(axis=1))
cp.loc[cp['change'].idxmax(),'CTYNAME']

'Harris County'

In [73]:
def answer_seven():
    cp = census_df[census_df['SUMLEV']==50].loc[:,'CTYNAME':'POPESTIMATE2015']
    cp['change'] = abs(cp.loc[:,'POPESTIMATE2010':'POPESTIMATE2015'].max(axis=1)-cp.loc[:,'POPESTIMATE2010':'POPESTIMATE2015'].min(axis=1))
    return cp.loc[cp['change'].idxmax(),'CTYNAME']
answer_seven()

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [88]:
cdf = census_df[(census_df['REGION']==1) | (census_df['REGION']==2)][census_df['POPESTIMATE2015']>census_df['POPESTIMATE2014']]
cdf[['STNAME','CTYNAME']][cdf['CTYNAME'].str[:10]=='Washington']

C:\Users\wanli\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [11]:
def answer_eight():
    cdf = census_df[(census_df['REGION']==1) | (census_df['REGION']==2)][census_df['POPESTIMATE2015']>census_df['POPESTIMATE2014']]
    return cdf[['STNAME','CTYNAME']][cdf['CTYNAME'].str[:10]=='Washington']